import type { Battery, HeatPump } from "../types";

// Homate battery catalog — 5 werkelijke pakketten.
// Bron: Products.xlsx (intern Homate catalogus, april 2026).
// `priceIncl` = publieksprijs incl. 21% BTW + installatie (kolom "BTW 21% retail").
// Voor gebouwen >10 jaar geldt in BE 6% BTW — dat tonen we bij de prijsindicatie
// als aparte korting, niet hier in de catalogus.
export const CATALOG: Battery[] = [
  {
    id: "dyness-5",
    brand: "Dyness",
    model: "5 kWh batterijpakket + Solis 5 kW retrofit",
    capacityKwh: 5,
    usableKwh: 5,
    tier: "entry",
    priceIncl: 3099,
    warrantyYears: 10,
    backup: false,
    inverterKw: 5,
    cycles: 6000,
    imageUrl: "https://cdn.prod.website-files.com/6549f080cad14f949be770d8/69b970ebd55b07a7f3f87bdb_DYN_5.png",
    highlights: [
      "Scherpste instappakket van de catalogus",
      "Solis 5 kW retrofit-omvormer — koppelt op bestaande PV",
      "LiFePO4-chemie, 6.000 cycli, 10 jaar garantie",
    ],
    bestFor: "Kleinere verbruikers die hun avondpiek willen wegwerken zonder groot budget.",
  },
  {
    id: "dyness-10",
    brand: "Dyness",
    model: "10 kWh batterijpakket + Solis 3 kW retrofit",
    capacityKwh: 10,
    usableKwh: 10,
    tier: "mid",
    priceIncl: 4199,
    warrantyYears: 10,
    backup: false,
    inverterKw: 3,
    cycles: 6000,
    imageUrl: "https://cdn.prod.website-files.com/6549f080cad14f949be770d8/69b970ebf2ee47889e678af1_DYN_10.png",
    highlights: [
      "Meest gekozen Dyness-configuratie",
      "Dekt typisch avondverbruik van een Belgisch gezin",
      "Ideaal op dynamisch tarief voor energie-arbitrage",
    ],
    bestFor: "Gezinnen met 3.500–5.500 kWh verbruik die maximaal zelfverbruik zoeken.",
  },
  {
    id: "alphaess-9",
    brand: "Alpha ESS",
    model: "9,3 kWh batterijpakket + EMS (5 kW retrofit)",
    capacityKwh: 9.3,
    usableKwh: 9.3,
    tier: "mid",
    priceIncl: 6049,
    warrantyYears: 10,
    backup: false,
    inverterKw: 5,
    cycles: 10000,
    imageUrl: "https://cdn.prod.website-files.com/6549f080cad14f949be770d8/69b970ebd50b70e7a8840640_AESS_10.png",
    highlights: [
      "Ingebouwd energiebeheersysteem (EMS)",
      "Smart-grid-ready — koppelt met warmtepomp & EV",
      "10.000 cycli: hoogste levensduur in de catalogus",
    ],
    bestFor: "Wie slim wil sturen op warmtepomp, EV of dynamisch contract en lang wil meegaan.",
  },
  {
    id: "dyness-15",
    brand: "Dyness",
    model: "15 kWh batterijpakket + Solis 6 kW retrofit",
    capacityKwh: 15,
    usableKwh: 15,
    tier: "premium",
    priceIncl: 8099,
    warrantyYears: 10,
    backup: false,
    inverterKw: 6,
    cycles: 8000,
    imageUrl: "https://cdn.prod.website-files.com/6549f080cad14f949be770d8/69b970ec8fbe8927cab181b1_Powerbrick.png",
    highlights: [
      "Ruime opslag voor grote huishoudens",
      "Solis 6 kW retrofit-omvormer voor grotere PV-installaties",
      "8.000 cycli — uitstekende prijs/opslag-verhouding",
    ],
    bestFor: "Grote gezinnen, hoog verbruik of ambitieuze autarkie zonder Alpha-premie.",
  },
  {
    id: "alphaess-18",
    brand: "Alpha ESS",
    model: "18,6 kWh batterijpakket + EMS (5 kW retrofit)",
    capacityKwh: 18.6,
    usableKwh: 18.6,
    tier: "premium",
    priceIncl: 9299,
    warrantyYears: 10,
    backup: false,
    inverterKw: 5,
    cycles: 10000,
    imageUrl: "https://cdn.prod.website-files.com/6549f080cad14f949be770d8/69b970eb7d9c0c212f154238_AESS_18.png",
    highlights: [
      "Topmodel — dubbele opslag van de 9,3 kWh-versie",
      "EMS stuurt automatisch al je grote verbruikers aan",
      "10.000 cycli, 10 jaar product- én performance-garantie",
    ],
    bestFor: "Grote woningen met warmtepomp + EV die alles willen zelf opslaan en sturen.",
  },
];

export function catalogById(id: string): Battery | undefined {
  return CATALOG.find((b) => b.id === id);
}

// Homate heat-pump catalog — echte prijzen uit heatpulmps.csv.
// Alle modellen: Daikin Altherma 3, monobloc lucht/water, 180 L interne boiler,
// 2 jaar waarborg, 58 dB(A), €1.500 Mijn VerbouwPremie aftrekbaar.
// `priceIncl` bij default = 21% BTW-prijs; sizing.ts schakelt naar `priceIncl6`
// wanneer de woning ≥10 jaar oud is.
const DAIKIN_IMG = "https://cdn.prod.website-files.com/6549f080cad14f949be770d8/69e092bc2fde5f7cc3ae23c2_etvh-x-z-d-ip15.jpeg";
const COMMON_HIGHLIGHTS = [
  "Daikin Altherma 3 monobloc — bewezen betrouwbaar",
  "Ingebouwde 180 L boiler voor sanitair warm water",
  "Zeer stil (58 dB(A)) — geschikt voor rijwoningen",
  "A++ energielabel — hoog seizoensrendement",
];

export const HEAT_PUMP_CATALOG: HeatPump[] = [
  {
    id: "daikin-altherma3-4",
    code: "4WP",
    brand: "Daikin",
    model: "Altherma 3 — 4 kW met 180 L boiler",
    nominalKw: 4,
    scop: 4.5,
    efficiencyClass: "A++",
    dhwLiters: 180,
    tier: "entry",
    priceIncl21: 9149,
    priceIncl6: 8049,
    priceIncl: 9149,
    subsidyEur: 1500,
    savingsPerYearEur: 405,
    paybackYears21: 18.92,
    paybackYears6: 16.17,
    warrantyYears: 2,
    noiseDb: 58,
    suitableFor: ["radiators", "floor", "mix"],
    highlights: COMMON_HIGHLIGHTS,
    bestFor: "Compacte warmtepomp voor kleinere, goed geïsoleerde woningen. Verwarmt je huis én zorgt voor warm water uit één toestel.",
    imageUrl: DAIKIN_IMG,
  },
  {
    id: "daikin-altherma3-5",
    code: "5WP",
    brand: "Daikin",
    model: "Altherma 3 — 5 kW met 180 L boiler",
    nominalKw: 5,
    scop: 4.5,
    efficiencyClass: "A++",
    dhwLiters: 180,
    tier: "entry",
    priceIncl21: 8699,
    priceIncl6: 7649,
    priceIncl: 8699,
    subsidyEur: 1500,
    savingsPerYearEur: 550,
    paybackYears21: 13.08,
    paybackYears6: 11.17,
    warrantyYears: 2,
    noiseDb: 58,
    suitableFor: ["radiators", "floor", "mix"],
    highlights: COMMON_HIGHLIGHTS,
    bestFor: "Ideaal voor compacte nieuwbouw of goed gerenoveerde woningen. Verwarmen, koelen en warm water in één stil en zuinig toestel.",
    imageUrl: DAIKIN_IMG,
  },
  {
    id: "daikin-altherma3-6",
    code: "6WP",
    brand: "Daikin",
    model: "Altherma 3 — 6 kW met 180 L boiler",
    nominalKw: 6,
    scop: 4.5,
    efficiencyClass: "A++",
    dhwLiters: 180,
    tier: "mid",
    priceIncl21: 9149,
    priceIncl6: 8049,
    priceIncl: 9149,
    subsidyEur: 1500,
    savingsPerYearEur: 685,
    paybackYears21: 11.17,
    paybackYears6: 9.58,
    warrantyYears: 2,
    noiseDb: 58,
    suitableFor: ["radiators", "floor", "mix"],
    highlights: COMMON_HIGHLIGHTS,
    bestFor: "De gouden middenweg voor de gemiddelde gezinswoning. Werkt vlot met vloerverwarming én bestaande radiatoren.",
    imageUrl: DAIKIN_IMG,
  },
  {
    id: "daikin-altherma3-7",
    code: "7WP",
    brand: "Daikin",
    model: "Altherma 3 — 7 kW met 180 L boiler",
    nominalKw: 7,
    scop: 4.4,
    efficiencyClass: "A++",
    dhwLiters: 180,
    tier: "mid",
    priceIncl21: 9599,
    priceIncl6: 8449,
    priceIncl: 9599,
    subsidyEur: 1500,
    savingsPerYearEur: 860,
    paybackYears21: 9.42,
    paybackYears6: 8.08,
    warrantyYears: 2,
    noiseDb: 58,
    suitableFor: ["radiators", "floor", "mix"],
    highlights: COMMON_HIGHLIGHTS,
    bestFor: "Krachtige warmtepomp voor ruimere of minder geïsoleerde woningen. Perfect voor renovaties waar je je radiatoren wil behouden.",
    imageUrl: DAIKIN_IMG,
  },
  {
    id: "daikin-altherma3-85",
    code: "8,5WP",
    brand: "Daikin",
    model: "Altherma 3 — 8,5 kW met 180 L boiler",
    nominalKw: 8.5,
    scop: 4.3,
    efficiencyClass: "A++",
    dhwLiters: 180,
    tier: "premium",
    priceIncl21: 14149,
    priceIncl6: 12449,
    priceIncl: 14149,
    subsidyEur: 1500,
    savingsPerYearEur: 1090,
    paybackYears21: 11.58,
    paybackYears6: 10.08,
    warrantyYears: 2,
    noiseDb: 58,
    suitableFor: ["radiators", "floor", "mix"],
    highlights: COMMON_HIGHLIGHTS,
    bestFor: "Stevige warmtepomp voor grotere woningen of een hogere warmtevraag. Stil, betrouwbaar en geschikt om je gasketel volledig te vervangen.",
    imageUrl: DAIKIN_IMG,
  },
  {
    id: "daikin-altherma3-10",
    code: "10WP",
    brand: "Daikin",
    model: "Altherma 3 — 10 kW met 180 L boiler",
    nominalKw: 10,
    scop: 4.3,
    efficiencyClass: "A++",
    dhwLiters: 180,
    tier: "premium",
    priceIncl21: 14599,
    priceIncl6: 12849,
    priceIncl: 14599,
    subsidyEur: 1500,
    savingsPerYearEur: 1320,
    paybackYears21: 9.92,
    paybackYears6: 8.58,
    warrantyYears: 2,
    noiseDb: 58,
    suitableFor: ["radiators", "floor", "mix"],
    highlights: COMMON_HIGHLIGHTS,
    bestFor: "Het topmodel voor grote of energieverslindende woningen. Vervangt moeiteloos je gasketel.",
    imageUrl: DAIKIN_IMG,
  },
];

export function heatPumpById(id: string): HeatPump | undefined {
  return HEAT_PUMP_CATALOG.find((hp) => hp.id === id);
}
